DOMAIN = "couple_calendar"
PANEL_URL = "couple-calendar"
PANEL_TITLE = "Couple Calendar"
PANEL_ICON = "mdi:calendar-heart"
STATIC_PATH = "couple_calendar_static"

CONF_PERSON_A_NAME = "person_a_name"
CONF_PERSON_A_COLOR = "person_a_color"
CONF_PERSON_A_CALENDAR = "person_a_calendar"
CONF_PERSON_B_NAME = "person_b_name"
CONF_PERSON_B_COLOR = "person_b_color"
CONF_PERSON_B_CALENDAR = "person_b_calendar"
CONF_JOINT_CALENDAR = "joint_calendar"
CONF_JOINT_COLOR = "joint_color"
CONF_FIRST_DAY_OF_WEEK = "first_day_of_week"
CONF_TIME_FORMAT = "time_format"
CONF_DEFAULT_VIEW = "default_view"
CONF_SHOW_WEEKENDS = "show_weekends"
CONF_THEME = "theme"

DEFAULT_PERSON_A_COLOR = "#818CF8"
DEFAULT_PERSON_B_COLOR = "#F472B6"
DEFAULT_JOINT_COLOR = "#34D399"
DEFAULT_FIRST_DAY_OF_WEEK = 0  # Sunday
DEFAULT_TIME_FORMAT = "12h"
DEFAULT_DEFAULT_VIEW = "month"
DEFAULT_THEME = "dark"
